#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server

args=$#
filepath=$1
ip=$2
username=$3
privkey=$4
comm="scp -o StrictHostKeyChecking=no -i '$4' '$1' '$3'@'$2':/home/'$3'"
# scp -o StrictHostKeyChecking=no -i ~/keys/id_rsa some_page.html ubuntu@54.172.54.224:/home/ubuntu

if [ $args -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    eval $comm
    #scp -o StrictHostKeyChecking=no -i "$privkey" "$filepath" "$username@$ip":~/
fi
