#!/usr/bin/env bash
# A# Configure your Nginx server so that /redirect_me is redirecting to another page

# Update Ubuntu and install Nginx
#sudo apt-get -y update
#sudo apt-get -y install nginx

# Start the Nginx service
#sudo service nginx start

# Allow Nginx through the firewall
#sudo ufw allow 'Nginx HTTP'


# Create an index.html file
#echo 'Hello World!' | sudo tee /var/www/html/index.html

#string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
#sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Creating the 404 error page
#echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Directing 404 error to custom page
#rep_str="\terror_page 404 /404.html;\n \tlocation = /404.html {\n \t\troot /var/www/html;\n \t\tinternal;"
#sudo sed -i "s|^[^#].*location \/ {$|$rep_str|" /etc/nginx/sites-enabled/default;

#try_str="\t\t# try_files \$uri \$uri =404;"
#sudo sed -i "s/^.*[^#]try_files.*/$try_str/" /etc/nginx/sites-enabled/default;

# Restart Nginx services
#sudo service nginx restart

#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page

# Installing nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Editing the index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Redirecting a specific page
new_string="\tserver_name _;\n \trewrite ^/redirect_me/$ http://x.com permanent;\n \trewrite ^/redirect_me$ http://x.com permanent; "
sudo sed -i "s|^[^#].*server_name.*;|$new_string|" /etc/nginx/sites-enabled/default;

# Creating the 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Directing 404 error to custom page
rep_str="\terror_page 404 /404.html;\n \tlocation = /404.html {\n \t\troot /var/www/html;\n \t\tinternal;"
sudo sed -i "s|^[^#].*location \/ {$|$rep_str|" /etc/nginx/sites-enabled/default;

try_str="\t\t# try_files \$uri \$uri =404;"
sudo sed -i "s/^.*[^#]try_files.*/$try_str/" /etc/nginx/sites-enabled/default;

# Removing temporary files being saved in the same directory
# This causes the nginx server to fail, because their are
# two default servers in two different files
sudo rm -rf /etc/nginx/sites-enabled/default~

# Restarting ngnix server to load up changes
sudo service nginx restart
