#!/usr/bin/env bash
#a Bash script that configures the container to run nginx as nginx user

# Stop Nginx if already running
sudo service nginx stop

# Configure Nginx to run as nginx user
chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf

# Configure Nginx to listen on all active IPs on port 8080
sed -i 's/listen 80 default_server/listen 8080 default_server/g' /etc/nginx/sites-available/default
sed -i 's/listen [::]:80 default_server/listen [::]:8080 default_server/g' /etc/nginx/sites-available/default

# Start Nginx
#su nginx -c "service nginx restart"
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
